version: '3'

services:
  client:
    build:
      context: client
      target: development
    networks:
      - client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/code/src:ro

  server:
    build:
      context: server
      target: development
    environment:
      - ADDRESS=0.0.0.0:8000
      - RUST_LOG=debug
      - PG_DBNAME=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=mysecretpassword
    ports:
      - 8000:8000
    networks:
      - client
      - server
    volumes:
      - ./server/src:/code/src
      - server-cache:/code/target
    depends_on:
      - db

  db:
    image: postgres:12-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    networks:
      - server
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

networks:
  client: {}
  server: {}

volumes:
  server-cache: {}
  db-data: {}
